#!/bin/bash
set -e

BUILD=${BUILD:-1}
if [[ -z "${DIST:-}" ]]; then
  echo >&2 "\$DIST not specified; aborting package build"
  exit 1
fi
if [[ -z "${VERSION:-}" ]]; then
  echo >&2 "\$VERSION not specified; aborting package build"
  exit 1
fi

git clone https://github.com/filefrog/ctap
cd ctap
git checkout static
./bootstrap
./configure
make dist

mkdir -p /tmp/d/work
cp ctap-${VERSION}.tar.gz /tmp/d/ctap_${VERSION}.orig.tar.gz
cp -a debian/ /tmp/d/work/debian

cd /tmp/d/work
tar -xz --strip-components 1 -f ../ctap_${VERSION}.orig.tar.gz
cat <<EOF > debian/changelog
ctap (${VERSION}-${BUILD}) ${DIST}; urgency=low

  * package

 -- Docker Packager <packages@niftylogic.com>  $(date +"%a, %d %b %Y %H:%M:00 %z")
EOF
debuild -i -us -uc -S
(cd .. && mk-build-deps -ir ctap_${VERSION}-${BUILD}.dsc)
debuild -i -us -uc -b
mkdir -p /srv/${DIST}
cp -a ../*.deb /srv/${DIST}
