#!/bin/bash
set -e

BUILD=${BUILD:-1}
if [[ -z "${DIST:-}" ]]; then
  echo >&2 "\$DIST not specified; aborting package build"
  exit 1
fi
if [[ -z "${VERSION:-}" ]]; then
  echo >&2 "\$VERSION not specified; aborting package build"
  exit 1
fi

mkdir -p /srv/${DIST}

cd ${HOME}
curl -LO https://github.com/jhunt/ctap/releases/download/v${VERSION}/ctap-${VERSION}.tar.gz

case ${FLAVOR} in
(debuild)
  cp ctap-${VERSION}.tar.gz ${HOME}/ctap_${VERSION}.orig.tar.gz
  cp -a /srv/debian/ ${HOME}/debuild/debian

  cd ${HOME}/debuild
  tar -xz --strip-components 1 -f ../ctap_${VERSION}.orig.tar.gz
  debuild -i -us -uc -b
  cp -a ../*.deb /srv/${DIST}
  ;;

(rpmbuild)
  cp ctap-${VERSION}.tar.gz ${HOME}/rpm
  rpmbuild -bb /srv/rpm.spec
  cp -a ${HOME}/rpm/x86_64/*.rpm /srv/${DIST}
  ;;

(*)
  echo >&2 "UNHANDLED FLAVOR \`${FLAVOR}'!"
  exit 2
  ;;
esac

echo "SUCCESS"
exit 0
