#!/bin/bash
set -e

BUILD=${BUILD:-1}
BRANCH=${BRANCH:-master}
if [[ -z "${DIST:-}" ]]; then
  echo >&2 "\$DIST not specified; aborting package build"
  exit 1
fi
if [[ -z "${VERSION:-}" ]]; then
  echo >&2 "\$VERSION not specified; aborting package build"
  exit 1
fi

mkdir -p /srv/${DIST}

case "${FLAVOR}" in
(debuild)
  curl -s https://packagecloud.io/install/repositories/bolo/bolo/script.deb.sh | sudo bash
  sudo apt-get install -y ctap libsodium-dev libsodium13 libzmq-dev libzmq5 pkg-config
  ;;

(rpmbuild)
  curl -s https://packagecloud.io/install/repositories/bolo/bolo/script.rpm.sh | sudo bash
  case "${DIST}" in
  (el5|el6)
    echo "${DIST} requires a newer version of autoconf than is provided upstream"
    echo "Pulling down from packagecloud..."
    sudo yum install -y autoconf-2.69 automake-1.15 libtool-2.4.6
    ;;
  esac

  sudo yum install -y ctap libsodium-devel libsodium libzmq-devel libzmq pkgconfig
  ;;

(*)
  echo >&2 "UNHANDLED FLAVOR \`${FLAVOR}'!"
  exit 2
  ;;
esac


cd ${HOME}
git clone https://github.com/filefrog/libvigor
cd libvigor
git checkout ${BRANCH}
./bootstrap
./configure
make dist

case ${FLAVOR} in
(debuild)
  cp libvigor-${VERSION}.tar.gz ${HOME}/libvigor_${VERSION}.orig.tar.gz
  cp -a debian/ ${HOME}/debuild/debian

  cd ${HOME}/debuild
  tar -xz --strip-components 1 -f ../libvigor_${VERSION}.orig.tar.gz
  cat <<EOF > debian/changelog
libvigor (${VERSION}-${BUILD}) ${DIST}; urgency=low

  * package

 -- Docker Packager <packages@niftylogic.com>  $(date +"%a, %d %b %Y %H:%M:00 %z")
EOF
  debuild -i -us -uc -b
  cp -a ../*.deb /srv/${DIST}
  ;;

(rpmbuild)
  cp libvigor-${VERSION}.tar.gz ${HOME}/rpm
  rpmbuild -bb rpm.spec
  cp -a ${HOME}/rpm/x86_64/*.rpm /srv/${DIST}
  ;;

esac

echo "SUCCESS"
exit 0
