#!/bin/bash
set -eu
NAME=libvigor
VERSION=1.2.10
ARCHIVE=${NAME}-${VERSION}.tar.gz
SOURCE_URL=https://github.com/jhunt/${NAME}/releases/download/v${VERSION}/${ARCHIVE}

for var in FLAVOR DIST; do
	val=$(eval echo \$$var)
	if [[ -z $val ]]; then
		echo >&2 "\$$var not defined in environment (are you in the rpmbuild/debuid Docker container?)"
		exit 1
	fi
done

cd ${HOME}
curl -LO ${SOURCE_URL}

sudo mkdir -p /pub/${OS}/${DIST}/
case ${FLAVOR} in
(debuild)
  curl -Ls http://pkg.niftylogic.com/setup | sudo sh
  sudo apt-get update
  sudo apt-get install -y ctap libsodium-dev libsodium13 libzmq-dev libzmq5

  cp ${ARCHIVE} ${HOME}/${NAME}_${VERSION}.orig.tar.gz
  cp -a /srv/debian/ ${HOME}/debuild/debian
  sed -i -e "s/ unstable; urgency=/ ${DIST}; urgency=/" ${HOME}/debuild/debian/changelog

  cd ${HOME}/debuild
  tar -xz --strip-components 1 -f ../${NAME}_${VERSION}.orig.tar.gz
  debuild -i -us -uc -b
  find .. -name '*.deb' -o -name '*.dsc' -o -name '*.tar.gz' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(rpmbuild)
  curl -Ls http://pkg.niftylogic.com/setup | sudo sh
  sudo yum install -y ctap libsodium-devel libsodium libzmq-devel libzmq

  cp ${ARCHIVE} ${HOME}/rpm
  rpmbuild -ba /srv/rpm.spec
  find .. -name '*.rpm' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(*)
  echo >&2 "UNHANDLED FLAVOR \`${FLAVOR}'!"
  exit 2
  ;;
esac

echo "SUCCESS"
exit 0
