#!/bin/bash
set -eu
NAME=bolo
VERSION=0.2.18
ARCHIVE=${NAME}-${VERSION}.tar.gz
SOURCE_URL=https://github.com/bolo/${NAME}/releases/download/v${VERSION}/${ARCHIVE}

for var in FLAVOR DIST; do
	val=$(eval echo \$$var)
	if [[ -z $val ]]; then
		echo >&2 "\$$var not defined in environment (are you in the rpmbuild/debuid Docker container?)"
		exit 1
	fi
done

cd ${HOME}
curl -LO ${SOURCE_URL}

tar -xzf $ARCHIVE
pushd ${NAME}-${VERSION}
sed -i -e 's/$BOLO $OPTIONS/$BOLO aggr $OPTIONS/' redhat/init.d/bolo
sed -i -e 's/^dumpfiles/#dumpfiles/' examples/bolo.conf
echo '@20s /usr/lib/bolo/collectors/linux' > examples/dbolo.conf
popd
tar -czf $ARCHIVE ${NAME}-${VERSION}/

sudo mkdir -p /pub/${OS}/${DIST}/
case ${FLAVOR} in
(debuild)
  curl -Ls http://pkg.niftylogic.com/setup | sudo sh
  sudo apt-get update
  sudo apt-get install -y \
    ctap \
    libsodium-dev libsodium13 \
    libzmq-dev libzmq5 \
    libhiredis-dev libhiredis0.13 \
    libncurses5-dev libncursesw5 \
    librrd-dev librrd8 \
    libpq-dev libpq5 \
    libvigor-dev libvigor1
  # ugly hack
  sudo mkdir /usr/include/ncursesw
  sudo cp -a /usr/include/*curses.h /usr/include/ncursesw/
  # another ugly hack
  sudo cp -a /usr/lib/x86_64-linux-gnu/libncurses.so /usr/lib/x86_64-linux-gnu/libncursesw.so

  cp ${ARCHIVE} ${HOME}/${NAME}_${VERSION}.orig.tar.gz
  cp -a /srv/debian/ ${HOME}/debuild/debian
  sed -i -e "s/ unstable; urgency=/ ${DIST}; urgency=/" ${HOME}/debuild/debian/changelog

  cd ${HOME}/debuild
  tar -xz --strip-components 1 -f ../${NAME}_${VERSION}.orig.tar.gz
  debuild -i -us -uc -b
  find .. -name '*.deb' -o -name '*.dsc' -o -name '*.tar.gz' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(rpmbuild)
  curl -Ls http://pkg.niftylogic.com/setup | sudo sh
  sudo yum install -y \
    ctap \
    libsodium-devel libsodium \
    libzmq-devel libzmq \
    libvigor libvigor-devel \
    pcre-devel \
    rrdtool-devel \
    postgresql-devel \
    libhiredis-devel \
    ncurses-devel

  cp ${ARCHIVE} ${HOME}/rpm
  rpmbuild -ba /srv/redhat/rpm.spec
  find .. -name '*.rpm' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(*)
  echo >&2 "UNHANDLED FLAVOR \`${FLAVOR}'!"
  exit 2
  ;;
esac

echo "SUCCESS"
exit 0
