#!/bin/bash
set -e

BUILD=${BUILD:-1}
if [[ -z "${DIST:-}" ]]; then
  echo >&2 "\$DIST not specified; aborting package build"
  exit 1
fi
if [[ -z "${VERSION:-}" ]]; then
  echo >&2 "\$VERSION not specified; aborting package build"
  exit 1
fi

curl -s https://packagecloud.io/install/repositories/bolo/bolo/script.deb.sh | sudo bash
sudo apt-get install libsodium-dev libsodium13 pkg-config

cd ${HOME}
curl -sO http://download.zeromq.org/zeromq-${VERSION}.tar.gz

mkdir -p ${HOME}/d/work
cp zeromq-${VERSION}.tar.gz ${HOME}/d/zeromq_${VERSION}.orig.tar.gz
cp -a /srv/debian/ ${HOME}/d/work/debian

cd ${HOME}/d/work
tar -xz --strip-components 1 -f ../zeromq_${VERSION}.orig.tar.gz
cat <<EOF > debian/changelog
zeromq (${VERSION}-${BUILD}) ${DIST}; urgency=low

  * package

 -- Docker Packager <packages@niftylogic.com>  $(date +"%a, %d %b %Y %H:%M:00 %z")
EOF

debuild -i -us -uc -b
mkdir -p /srv/${DIST}
cp -a ../*.deb /srv/${DIST}
