#!/bin/bash
set -eu
NAME=libzmq
VERSION=4.1.5
ARCHIVE=zeromq-${VERSION}.tar.gz
#SOURCE_URL=http://download.zeromq.org/${ARCHIVE}
SOURCE_URL=https://github.com/zeromq/zeromq4-1/releases/download/v${VERSION}/${ARCHIVE}

for var in FLAVOR DIST; do
	val=$(eval echo \$$var)
	if [[ -z $val ]]; then
		echo >&2 "\$$var not defined in environment (are you in the rpmbuild/debuid Docker container?)"
		exit 1
	fi
done

cd ${HOME}
curl -LO ${SOURCE_URL}

sudo mkdir -p /pub/${OS}/${DIST}/
case ${FLAVOR} in
(debuild)
  sudo curl -L -o /etc/apt/sources.list.d/niftylogic.list \
    http://pkg.niftylogic.com/${OS}/${DIST}/niftylogic.list
  sudo apt-get update
  sudo apt-get install -y --force-yes libsodium-dev libsodium13

  cp ${ARCHIVE} ${HOME}/${NAME}_${VERSION}.orig.tar.gz
  cp -a /srv/debian/ ${HOME}/debuild/debian
  sed -i -e "s/ unstable; urgency=/ ${DIST}; urgency=/" ${HOME}/debuild/debian/changelog

  cd ${HOME}/debuild
  tar -xz --strip-components 1 -f ../${NAME}_${VERSION}.orig.tar.gz
  DEB_BUILD_OPTIONS=parallel=4 debuild -i -us -uc -b
  find .. -name '*.deb' -o -name '*.dsc' -o -name '*.tar.gz' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(rpmbuild)
  sudo curl -L -o /etc/yum.repos.d/niftylogic.repo \
    http://pkg.niftylogic.com/centos/niftylogic.repo
  sudo yum install -y libsodium-devel libsodium

  cp ${ARCHIVE} ${HOME}/rpm
  rpmbuild -ba /srv/rpm.spec
  find .. -name '*.rpm' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(*)
  echo >&2 "UNHANDLED FLAVOR \`${FLAVOR}'!"
  exit 2
  ;;
esac

echo "SUCCESS"
exit 0
