#!/bin/bash
set -eu
NAME=rrdtool
VERSION=1.6.0
ARCHIVE=${NAME}-${VERSION}.tar.gz
SOURCE_URL=http://oss.oetiker.ch/rrdtool/pub/${ARCHIVE}

for var in FLAVOR DIST; do
	val=$(eval echo \$$var)
	if [[ -z $val ]]; then
		echo >&2 "\$$var not defined in environment (are you in the rpmbuild/debuid Docker container?)"
		exit 1
	fi
done

cd ${HOME}
curl -LO ${SOURCE_URL}

sudo mkdir -p /pub/${OS}/${DIST}/
case ${FLAVOR} in
(debuild)
  cp ${ARCHIVE} ${HOME}/${NAME}_${VERSION}.orig.tar.gz
  cp -a /srv/debian/ ${HOME}/debuild/debian

  cd ${HOME}/debuild
  tar -xz --strip-components 1 -f ../${NAME}_${VERSION}.orig.tar.gz
  debuild -i -us -uc -b
  find .. -name '*.deb' -o -name '*.dsc' -o -name '*.tar.gz' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(rpmbuild)
  sudo curl -L -o /etc/yum.repos.d/niftylogic.repo \
    http://pkg.niftylogic.com/centos/niftylogic.repo
  sudo yum install -y \
    gcc-c++ \
    openssl-devel \
    freetype-devel \
    libpng-devel \
    zlib-devel \
    intltool \
    cairo-devel \
    pango-devel \
    libtool \
    groff \
    gettext \
    libxml2-devel \
    pcre-devel

  case ${DIST} in
  (el6|el7)
    sudo yum install -y perl-ExtUtils-MakeMaker
    ;;
  esac

  cp ${ARCHIVE} ${HOME}/rpm
  rpmbuild -ba /srv/rpm.spec
  find .. -name '*.rpm' |\
    xargs -I@ sudo cp @ /pub/${OS}/${DIST}
  ;;

(*)
  echo >&2 "UNHANDLED FLAVOR \`${FLAVOR}'!"
  exit 2
  ;;
esac

echo "SUCCESS"
exit 0
