#!/bin/bash
set -e

BUILD=${BUILD:-1}
if [[ -z "${DIST:-}" ]]; then
  echo >&2 "\$DIST not specified; aborting package build"
  exit 1
fi

case ${FLAVOR} in
(debuild)
  echo "Debian / Ubuntu platforms don't need newer autotools"
  ;;

(rpmbuild)
  AUTOCONF_VERSION=2.69
  AUTOMAKE_VERSION=1.15

  mkdir -p /srv/${DIST}
  cd ${HOME}/rpm
  curl -LO http://ftp.gnu.org/gnu/autoconf/autoconf-${AUTOCONF_VERSION}.tar.gz
  curl -LO http://ftp.gnu.org/gnu/automake/automake-${AUTOMAKE_VERSION}.tar.gz

  rpmbuild -bb /srv/autoconf.spec
  find ${HOME}/rpm/x86_64 -type f -name '*.rpm' | xargs sudo rpm -Uvh

  rpmbuild -bb /srv/automake.spec

  cp -a ${HOME}/rpm/x86_64/*.rpm /srv/${DIST}
  ;;

(*)
  echo >&2 "UNHANDLED FLAVOR \`${FLAVOR}'!"
  exit 2
  ;;
esac

echo "SUCCESS"
exit 0
